; Projekt: repeater — sieć mesh WiFi na Seeed XIAO ESP32-C3 (painlessMesh)
; Wersja: 2026-06-14 16:30

[env:seeed_xiao_esp32c3]
platform = espressif32
board = seeed_xiao_esp32c3
framework = arduino
monitor_speed = 115200
lib_deps =
    painlessMesh
    ArduinoJson@^6
    TaskScheduler
